-- Таблица requests
CREATE TABLE IF NOT EXISTS requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    requester_id BIGINT NOT NULL,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status request_status NOT NULL,
    CONSTRAINT fk_request_to_event FOREIGN KEY(event_id) REFERENCES events(id),
    CONSTRAINT fk_request_to_user FOREIGN KEY(requester_id) REFERENCES users(id),
    CONSTRAINT uq_request UNIQUE (event_id, requester_id)
);
